import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    backgroundImage: {
      flex: 1,
    },
    container: {
      flex: 1,
      backgroundColor: 'rgba(18, 18, 18, 0.63)',
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 15,
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    },
    headerTitle: {
      fontSize: 22,
      fontWeight: 'bold',
      color: '#FFFFFF',
    },
    refreshButton: {
      padding: 5,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    loadingText: {
      marginTop: 15,
      color: '#FFFFFF',
      fontSize: 16,
    },
    reportContainer: {
      flex: 1,
      padding: 15,
    },
    summaryCard: {
      backgroundColor: 'rgba(30, 30, 30, 0.9)',
      borderRadius: 12,
      padding: 18,
      marginBottom: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      elevation: 5,
    },
    summaryHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 10,
    },
    summaryTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#FFFFFF',
    },
    summaryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 8,
      paddingVertical: 5,
    },
    summaryLabel: {
      color: '#CCCCCC',
      fontSize: 16,
    },
    summaryValue: {
      fontWeight: 'bold',
      color: '#FFFFFF',
      fontSize: 16,
    },
    periodText: {
      fontSize: 13,
      color: '#AAAAAA',
      marginTop: 8,
      textAlign: 'right',
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      marginBottom: 15,
      marginTop: 5,
      color: '#FFFFFF',
    },
    dayCard: {
      backgroundColor: 'rgba(30, 30, 30, 0.6)',
      borderRadius: 12,
      padding: 15,
      marginBottom: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 3,
      elevation: 2,
      opacity: 0.8,
    },
    dayCardActive: {
      backgroundColor: 'rgba(40, 40, 40, 0.9)',
      borderRadius: 12,
      padding: 15,
      marginBottom: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 3,
      borderLeftWidth: 4,
      borderLeftColor: '#E53935',
    },
    dayHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    dayName: {
      fontWeight: 'bold',
      fontSize: 16,
      color: '#FFFFFF',
      flex: 2,
    },
    dayDate: {
      fontSize: 14,
      color: '#CCCCCC',
      flex: 1,
      textAlign: 'center',
    },
    dayHoursContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 2,
      justifyContent: 'flex-end',
    },
    dayHours: {
      fontSize: 14,
      fontWeight: 'bold',
      color: '#E53935',
      textAlign: 'right',
    },
    projectsList: {
      marginTop: 10,
      borderTopWidth: 1,
      borderTopColor: 'rgba(255, 255, 255, 0.1)',
      paddingTop: 10,
    },
    projectRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 8,
      paddingVertical: 5,
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(255, 255, 255, 0.05)',
    },
    projectName: {
      flex: 3,
      fontSize: 14,
      color: '#FFFFFF',
    },
    projectHours: {
      flex: 1,
      textAlign: 'right',
      fontSize: 14,
      color: '#FFFFFF',
    },
    boldText: {
      fontWeight: 'bold',
    },
    addButton: {
      backgroundColor: 'rgba(76, 175, 80, 0.9)',
      width: 28,
      height: 28,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
      marginLeft: 8,
    },
    historyButton: {
      backgroundColor: 'rgba(229, 57, 53, 0.9)',
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 25,
      margin: 15,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
      elevation: 3,
    },
    historyButtonText: {
      color: '#FFFFFF',
      fontWeight: 'bold',
      fontSize: 16,
      marginLeft: 8,
    },
    historyIcon: {
      marginRight: 5,
    },
    pdfButton: {
      backgroundColor: '#E53935',
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 8,
      paddingHorizontal: 15,
      borderRadius: 20,
      marginBottom: 15,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 3,
      elevation: 3,
    },
    pdfButtonText: {
      color: '#FFFFFF',
      fontWeight: 'bold',
      fontSize: 14,
      marginLeft: 5,
    },
    pdfIcon: {
      marginRight: 5,
    },
    modalContainer: {
      flex: 1,
      backgroundColor: 'rgba(18, 18, 18, 0.95)',
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 15,
      borderBottomWidth: 1,
      borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#FFFFFF',
    },
    closeButton: {
      padding: 5,
    },
    historyListContainer: {
      padding: 15,
    },
    historyItem: {
      backgroundColor: 'rgba(30, 30, 30, 0.8)',
      padding: 15,
      borderRadius: 12,
      marginBottom: 12,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 3,
      elevation: 2,
    },
    historyItemTitle: {
      fontWeight: 'bold',
      fontSize: 16,
      color: '#FFFFFF',
      marginBottom: 10,
    },
    historyItemRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 5,
    },
    historyItemLabel: {
      color: '#CCCCCC',
      fontSize: 14,
    },
    historyItemValue: {
      color: '#FFFFFF',
      fontSize: 14,
    },
    historyItemTotal: {
      color: '#E53935',
      fontWeight: 'bold',
    },
    savedAtText: {
      fontSize: 12,
      color: '#AAAAAA',
      marginTop: 8,
      textAlign: 'right',
    },
    detailsContainer: {
      flex: 1,
      padding: 15,
    },
    detailsTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      marginBottom: 20,
      textAlign: 'center',
      color: '#FFFFFF',
    },
    backButton: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 15,
      padding: 5,
    },
    backButtonText: {
      color: '#4285F4',
      fontWeight: 'bold',
      marginLeft: 5,
      fontSize: 16,
    },
    emptyContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 30,
    },
    emptyText: {
      color: '#AAAAAA',
      fontSize: 16,
      marginTop: 15,
      textAlign: 'center',
    },
    centeredModal: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0,0,0,0.7)',
    },
    modalContent: {
      backgroundColor: 'rgba(30, 30, 30, 0.95)',
      padding: 20,
      borderRadius: 12,
      width: '85%',
      borderLeftWidth: 4,
      borderLeftColor: '#E53935',
    },
    modalSubtitle: {
      fontSize: 14,
      color: '#AAAAAA',
      marginBottom: 20,
      textAlign: 'center',
    },
    input: {
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.2)',
      borderRadius: 8,
      padding: 12,
      marginBottom: 20,
      fontSize: 16,
      color: '#FFFFFF',
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
    },
    modalButtons: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    modalButton: {
      padding: 12,
      borderRadius: 8,
      width: '48%',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 3,
      elevation: 2,
    },
    cancelButton: {
      backgroundColor: 'rgba(244, 67, 54, 0.9)',
    },
    saveButton: {
      backgroundColor: 'rgba(76, 175, 80, 0.9)',
    },
    modalButtonText: {
      color: '#FFFFFF',
      fontWeight: 'bold',
      fontSize: 16,
    },
});